[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#fff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
textColor = "#002b36"

[client]
toolbarMode = "minimal"